name: tugasmusicplayer
description: "Music Player with LRC Lyrics"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/audio/multo.mp3
    - assets/lyrics/multo.lrc
